const teamList = [
	{
		team: "Ekeberg",
		location: "Haugenstua Idrettshall",
		locationLink: "https://maps.app.goo.gl/BB7yVHCfRdtH3f266",
		instagram: null,
		website: "https://ekebergsk.com/ultimate/treningstider/",
		facebook: "https://www.facebook.com/groups/692866460789756",
		time: "Monday 20:30-22:30, Wednesday 21:00-22:30",
		info: "Practice times might change to 19:30-21:30 both days, depending on the bureaucracy",
		picture: null,
		color: "rgba(0, 243, 16, 0.1)",
	},
	{
		team: "Brickers",
		location: "Furuset",
		locationLink: "https://maps.app.goo.gl/t8c1uaQKv7pKMAxS9",
		instagram: "https://www.instagram.com/brickers.ultimate.frisbee/",
		website: "https://www.furuset.no/vare-idretter/ultimate-frisbee",
		facebook: "https://www.facebook.com/BrickersUltimateFrisbeeOslo/",
		time: "Monday 18:30-20:30, Thursday 18:30-20:30",
		info: "Mondays we practice on the Ekeberg Beach Field, Thursdays on Ekebergs green, green grass.",
		picture: "/images/Brickers_Team_Picture.jpg",
		color: "background.blue",
	},
	{
		team: "Pancake",
		location: "Fjellhamarhallen",
		locationLink: "https://maps.app.goo.gl/aeuF5u5oge47hmoA8",
		instagram: "@test.pancake.insta",
		website: null,
		facebook: null,
		time: "Tuesday 19:30-21:30, Thursday 20:30-22:30, Sunday 17:00-21:00",
		info: "Practice times are lorem ipsum",
		picture: "/images/Pancake_Team_Picture.jpg",
		color: "rgba(243, 5, 21, 0.1)",
	},
	{
		team: "Bærum",
		location: "Kalvøya",
		locationLink: "https://maps.app.goo.gl/b6vUPsVHjxAeidbRA",
		instagram: null,
		website: "https://www.baerumfrisbeeklubb.no/next/p/70298/hjem",
		facebook: "https://www.facebook.com/profile.php?id=61564492610385",
		time: "Thursday 17:45",
		info: "More lorem ipsum for information testing. Is this gonna fit in the box? Let's see... ",
		picture: null,
		color: "rgba(243, 255, 194, 0.1)",
	},
	// {
	// 	team: "Wizards of Ås",
	// 	location: "EIKA SPORTSSENTER, Ås",
	// 	locationLink: "https://maps.app.goo.gl/JGJQpnfona3WLaB27",
	// 	instagram: null,
	// 	website: null,
	// 	facebook: "https://www.facebook.com/groups/574792535911770/",
	// 	time: "Tuesday 18:30-20:30, Friday 19:00-21:00",
	// 	info: 'Mainly for NMBU-students, no matter the experience. Tuesdays we practice in the "Gymnastikkhallen", Fridays in "GG-hallen".',
	// 	picture: null,
	// 	color: "rgba(0, 8, 243, 0.1)",
	// },
	{
		team: "OSI",
		location: "Athletica Blindern",
		locationLink: "https://maps.app.goo.gl/QbFowT8vBTgc5BFc8",
		instagram: null,
		website: "https://ultimate.osi.no/next/p/27975/news",
		facebook: "https://www.facebook.com/groups/125485077480296",
		time: "Wednesday 17:00 - 18:30",
		info: "",
		picture: null,
		color: "rgba(246, 164, 169, 0.1)",
	},
];

export default teamList;
