const practiceList = [
	{
		team: "Ekeberg",
		location: "Stovner",
		locationLink: null,
		instagram: null,
		website: null,
		facebook: null,
		time: "Tuesday 19:30-21:30, Thursday 20:30-22:30",
		info: "",
		picture: null,
		color: "rgba(0, 243, 16, 0.1)",
	},
	{
		team: "Brickers",
		location: "Furuset",
		locationLink: "https://maps.app.goo.gl/t8c1uaQKv7pKMAxS9",
		instagram: "https://www.instagram.com/brickers.ultimate.frisbee/",
		website: "https://www.furuset.no/vare-idretter/ultimate-frisbee",
		facebook: null,
		time: "Monday 18:30-20:30, Thursday 18:30-20:30",
		info: "Mondays on Ekeberg Beach FieldMondays on Ekeberg Beach FieldMondays on Ekeberg Beach FieldMondays on Ekeberg Beach FieldMondays on Ekeberg Beach FieldMondays on Ekeberg Beach FieldMondays on Ekeberg Beach FieldMondays on Ekeberg Beach FieldMondays on Ekeberg Beach FieldMondays on Ekeberg Beach FieldMondays on Ekeberg Beach FieldMondays on Ekeberg Beach FieldMondays on Ekeberg Beach FieldMondays on Ekeberg Beach FieldMondays on Ekeberg Beach FieldMondays on Ekeberg Beach FieldMondays on Ekeberg Beach FieldMondays on Ekeberg Beach FieldMondays on Ekeberg Beach FieldMondays on Ekeberg Beach FieldMondays on Ekeberg Beach FieldMondays on Ekeberg Beach FieldMondays on Ekeberg Beach FieldMondays on Ekeberg Beach FieldMondays on Ekeberg Beach FieldMondays on Ekeberg Beach FieldMondays on Ekeberg Beach FieldMondays on Ekeberg Beach FieldMondays on Ekeberg Beach FieldMondays on Ekeberg Beach FieldMondays on Ekeberg Beach FieldMondays on Ekeberg Beach FieldMondays on Ekeberg Beach FieldMondays on Ekeberg Beach FieldMondays on Ekeberg Beach FieldMondays on Ekeberg Beach FieldMondays on Ekeberg Beach FieldMondays on Ekeberg Beach FieldMondays on Ekeberg Beach Field",
		picture: "/images/Brickers_Team_Picture.jpg",
		color: "background.blue",
	},
	{
		team: "Pancake",
		location: "Fjellhamarhallen",
		locationLink: "https://maps.app.goo.gl/aeuF5u5oge47hmoA8",
		instagram: "@test.pancake.insta",
		website: null,
		facebook: null,
		time: "Tuesday 19:30-21:30, Thursday 20:30-22:30, Sunday 17:00-21:00",
		info: "Practice times are lorem ipsum",
		picture: "/images/Pancake_Team_Picture.jpg",
		color: "rgba(243, 5, 21, 0.1)",
	},
	{
		team: "Bærum",
		location: "Kalvøya",
		locationLink: null,
		instagram: null,
		website: null,
		facebook: null,
		time: "Tuesday 19:30-21:30, Thursday 20:30-22:30",
		info: "More lorem ipsum for information testing. Is this gonna fit in the box? Let's see... ",
		picture: null,
		color: "rgba(243, 243, 194, 0.1)",
	},
	{
		team: "Wizards of Ås",
		location: "Ås",
		locationLink: null,
		instagram: null,
		website: null,
		facebook: null,
		time: "Tuesday 19:30-21:30, Thursday 20:30-22:30",
		info: "",
		picture: null,
		color: "rgba(0, 8, 243, 0.1)",
	},
];

export default practiceList;
