const teamList = [
	{
		team: "The Oslo Community",
		location: ["Frognerparken"],
		locationLink: ["https://maps.app.goo.gl/Dx6VjPsqwZSuLstd9"],//["https://maps.app.goo.gl/YoekkkRC8DLBtWHBA"],
		instagram: "",
		website: "",
		facebook: "",
		time: "Monday 20:00-21:30",
		info: "A community pratice for all levels, where we go through drills and play lots of Ultimate. Everyone is welcome! We use the app \"Spond\" for updates and sign-ups.",
		picture: false,
		color: "rgba(236, 162, 242, 0.1)",
	},
	{
		team: "Ekeberg",
		location: [],//["Haugenstua Idrettshall"],
		locationLink: [],//["https://maps.app.goo.gl/BB7yVHCfRdtH3f266"],
		instagram: "https://www.instagram.com/ekebergsendeplateklubb/",
		website: "https://ekebergsk.com/ultimate/treningstider/",
		facebook: "https://www.facebook.com/groups/692866460789756",
		time: "",
		info: "Ekeberg does not have dedicated practices at the moment. You will find them at the various other practices around town! Please accept this poem instead...:  No field to claim, no set routine — Just borrowed drills on borrowed green. No field to call home, but still we show — Wherever discs fly high, we'll go. ",
		picture: true,
		color: "rgba(0, 243, 16, 0.1)",
	},
	{
		team: "Bærum",
		location: ["Kalvøya"],
		locationLink: ["https://maps.app.goo.gl/2cAWK32D3bQWJhpN9"],
		instagram: "https://www.instagram.com/baerumfrisbeeklubbultimate/",
		website: "https://www.baerumfrisbeeklubb.no/next/p/70298/hjem",
		facebook: "https://www.facebook.com/profile.php?id=61564492610385",
		time: "Thursday 18:00 - 20:00",
		info: "Oslos newest Ultimate team! Open for all to join.",
		picture: true,
		color: "rgba(192, 210, 64, 0.1)",
	},
	{
		team: "Pancake",
		location: [""],//["Fjellhamarhallen", "Kjenn-hallen", "Voldsløkka"],
		locationLink: [""],//["https://maps.app.goo.gl/aeuF5u5oge47hmoA8", "https://maps.app.goo.gl/1eWmVSvH8Cw7iXce8", "https://maps.app.goo.gl/x6dvGUbYCjdwHxL99"],
		instagram: "https://www.instagram.com/pancake_circle_ltd/",
		website: "https://www.pancake.no/next/p/70024/ultimate",
		facebook: "https://www.facebook.com/groups/109301512507959",
		time: "",
		info: "Indoor practices pending.",
		picture: true,
		color: "rgba(243, 5, 21, 0.1)",
	},
	{
		team: "Brickers",
		location: ["Furuset Forum"], //"Furuset Forum", 
		locationLink: ["https://maps.app.goo.gl/P5t68ctN8UoC2TCy8"], //"https://maps.app.goo.gl/P5t68ctN8UoC2TCy8",
		instagram: "https://www.instagram.com/brickers.ultimate.frisbee/",
		website: "https://www.furuset.no/vare-idretter/ultimate-frisbee",
		facebook: "https://www.facebook.com/BrickersUltimateFrisbeeOslo/",
		time: "Tuesday 21:00 - 22:30, Thursday 21:30 - 23:00",
		info: "Brickers is a competitive team that welcomes players of all levels. Everyone is welcome to come try the sport with us!",
		picture: true,
		color: "background.blue",
	},
		{
		team: "OSI",
		location: ["Athletica Blindern", "Oslo Met"],
		locationLink: ["https://maps.app.goo.gl/QbFowT8vBTgc5BFc8", "https://maps.app.goo.gl/8T5YiB3qRFgnoHHE8"],
		instagram: "https://www.instagram.com/osi_ultimate/",
		website: "https://ultimate.osi.no/next/p/27975/news",
		facebook: "https://www.facebook.com/groups/125485077480296",
		time: "Wednesday 17:00 - 18:30, Thursday 20:30 - 22:00",
		info: "Wednesdays at Athletica Blindern, Thursday at Oslo Met. If you are currently studying in Oslo, check out this great student team!",
		picture: true,
		color: "rgba(246, 164, 169, 0.1)",
	},
	
	// {
	// 	team: "Wizards of Ås",
	// 	location: "EIKA SPORTSSENTER, Ås",
	// 	locationLink: "https://maps.app.goo.gl/JGJQpnfona3WLaB27",
	// 	instagram: null,
	// 	website: null,
	// 	facebook: "https://www.facebook.com/groups/574792535911770/",
	// 	time: "Tuesday 18:30-20:30, Friday 19:00-21:00",
	// 	info: 'Mainly for NMBU-students, no matter the experience. Tuesdays we practice in the "Gymnastikkhallen", Fridays in "GG-hallen".',
	// 	picture: null,
	// 	color: "rgba(0, 8, 243, 0.1)",
	// },
];

export default teamList;
